### ISSUE TITLE
k线数据不够的时候，plotwidth会变得特别宽

### ISSUE THREAD

**Issue by nealsun** [zhiquan911/CHKLineChart#12]
如果k线数据很少，比如只有几个的时候，plotwidth根据range计算的结果会变得很大，因为这时候range等于全部的数据量。是不是需要限制一下最大plotwidth，或者plotwidth可以作为变量设置。

**Comment by zhiquan911** [comment]
plotwidth是根据点数量与图表宽度计算出来，现在绘图是完全填充的。如果要实现你的需求，需要代理增加设定图表最少线段，不足够做空白填充处理。
