### ISSUE TITLE
数据增多刷新的时候, 缩放还是按照之前很少数据的样式.

### ISSUE THREAD

**Issue by Zafirzzf** [zhiquan911/CHKLineChart#17]
还有新数据进来进行reload. 视图并没有跟随着右移加载,必须手滑...希望提供相关API

**Comment by zhiquan911** [comment]
//刷新数据，并移动到最后
chartView.reloadData(.end)

**Comment by Zafirzzf** [comment]
多谢，之前找到了。




| |
周飞
邮箱：zoolofty@163.com
|

签名由 网易邮箱大师 定制

在2018年08月17日 15:33，Chance 写道：

//刷新数据，并移动到最后
chartView.reloadData(.end)
