### ISSUE TITLE
当不设置chartView.style的时候，会崩溃

### ISSUE THREAD

**Issue by zjw7sky** [zhiquan911/CHKLineChart#4]
没有默认的style
![image](https://user-images.githubusercontent.com/8446716/38765311-9c89ba18-3ff1-11e8-9ef4-ff9c680fd161.png)

**Comment by zhiquan911** [comment]
style必须要设置一个默认的，已经有一个默认的.base的样式。 这里我完善一下，做可选检查。

**Comment by zjw7sky** [comment]
另外添加Section 必须 加series，不然就崩溃了
