### ISSUE TITLE
支持oc么

### ISSUE THREAD

**Issue by AllenDongCoder** [zhiquan911/CHKLineChart#5]
最好写个 oc版本的 ，不错

**Comment by renjiale1214** [comment]
同问，可以支持OC吗，需要SAR指标，自己去画有点费劲，尤其是本身已经用了别人的第三方库

**Comment by zhiquan911** [comment]
不好意思了大伙，苹果现在力推swift做iOS的原生开发，swift已升级得非常好靠了。同样的逻辑，swift代码写得更简洁，更易懂。建议iOS开发者都能够熟练使用swift，你可以用我的库集成到swift写的viewController上，通过OC通过XIB加载viewController就是。

**Comment by renjiale1214** [comment]
我自己画出SAR了。。。先顶着用吧，不想混编了。。。够够的
